export const cuisineList = [
    "Barbarian",
    "BBQ",
    "Breakfast",
    "Burgers",
    "Cafe",
    "Elemental",
    "Dessert",
    "Elvish",
    "Rogues' Diet",
    "Healthy",
    "Dwarven",
    "Druidic Brews",
    "Foraging",
    "Magically charged",
    "Noodles",
    "Organic",
    "Pasta",
    "Pizza",
    "Salads",
    "Seafood",
    "Sword Coast Specials",
    "Sushi",
    "Tacos",
    "Demonic Spirits",
    "Vegan",
]